# Generated by Django 4.0.6 on 2022-08-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('image', models.ImageField(upload_to='author')),
                ('surname', models.CharField(help_text='surname', max_length=100)),
                ('email', models.EmailField(help_text='email', max_length=254)),
                ('phone', models.CharField(help_text='phone', max_length=100)),
                ('website', models.URLField(help_text='website')),
                ('description', models.CharField(blank=True, help_text=300, max_length=300, null=True)),
                ('social_network', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='name', max_length=100, unique=True)),
                ('description', models.CharField(help_text='description', max_length=300)),
                ('image', models.ImageField(upload_to='category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='title', max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('description', models.CharField(help_text='description', max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('subtitle', models.CharField(help_text='subtitle', max_length=100)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('imagecontent', models.ImageField(upload_to='posts/imagecontent/')),
                ('content', models.TextField(help_text='content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.post')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.subcategory'),
        ),
    ]
